config:
  credentials: []
  project_repos:
    git.ufz.de/rdm-software/saqc:
      branch: main
      repo: https://git.ufz.de/rdm-software/saqc
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.ufz.de/rdm-software/saqc git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-cinnamon-echidna.sh
        container: qc.acc_flabby-pear-uguisu
  QC.Doc:
    repos:
      git.ufz.de/rdm-software/saqc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-scarlet-ferret.sh
        container: qc.doc_tacky-cyan-baboon
      git.ufz.de/rdm-software/saqc git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-lavender-labradoodle.sh
        container: qc.doc_chewy-platinum-lionfish
  QC.Lic:
    repos:
      git.ufz.de/rdm-software/saqc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-ruby-rabbit.sh
        container: qc.lic_geeky-cinnabar-sheep
  QC.Ver:
    repos:
      git.ufz.de/rdm-software/saqc get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-aquamarine-cheetah.sh
        container: qc.ver_flabby-lime-dane
timeout: 5400
