config:
  credentials: []
  project_repos:
    git.ufz.de/rdm-software/saqc:
      branch: main
      repo: https://git.ufz.de/rdm-software/saqc
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.ufz.de/rdm-software/saqc git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-chestnut-dingo.sh
        container: qc.acc_sunny-taupe-shark
  QC.Doc:
    repos:
      git.ufz.de/rdm-software/saqc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-lavender-jaguar.sh
        container: qc.doc_scaly-tan-hyena
      git.ufz.de/rdm-software/saqc git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-gold-deer.sh
        container: qc.doc_stinky-orchid-turkey
      git.ufz.de/rdm-software/saqc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-corn-rat.sh
        container: qc.doc_greasy-olivine-fox
      git.ufz.de/rdm-software/saqc restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-cinnabar-schnauzer.sh
        container: qc.doc_cranky-olivine-seahorse
  QC.Lic:
    repos:
      git.ufz.de/rdm-software/saqc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-magnolia-jackal.sh
        container: qc.lic_tasty-amaranth-snail
  QC.Met:
    repos:
      git.ufz.de/rdm-software/saqc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-amber-spaniel.sh
        container: qc.met_fuzzy-red-squirt
  QC.Sec:
    repos:
      git.ufz.de/rdm-software/saqc bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-taupe-vole.sh
        container: qc.sec_gummy-beige-ray
  QC.Sty:
    repos:
      git.ufz.de/rdm-software/saqc flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-harlequin-gecko.sh
        container: qc.sty_squeaky-cornflower-abyssinian
  QC.Ver:
    repos:
      git.ufz.de/rdm-software/saqc get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-crimson-buffalo.sh
        container: qc.ver_stuffy-cinnabar-raccoon
timeout: 5400
